package search;

public class BusRoutesTree {
    static TNode root = new TNode(0, "home", null, null, 0);
    static TNode nan1 = new TNode(1, "南村", null, null, 1);
    static TNode gong4 = new TNode(4, "公交新村", null, null, 2);
    static TNode gong2 = new TNode(2, "公交新村", null, null, 1);
    static TNode xiang11 = new TNode(11, "香宁花园", null, null, 3);
    static TNode xiang5 = new TNode(5, "香宁花园", null, null, 2);
    static TNode xiang8 = new TNode(8, "香宁花园", null, null, 2);
    static TNode xiang3 = new TNode(3, "香宁花园", null, null, 1);
    static TNode jiu23 = new TNode(23, "九洲城", null, null, 4);
    static TNode zhu12 = new TNode(12, "竹苑", null, null, 3);
    static TNode jiu13 = new TNode(13, "九洲城", null, null, 3);
    static TNode zhu6 = new TNode(6, "竹苑", null, null, 2);
    static TNode jiu18 = new TNode(18, "九洲城", null, null, 3);
    static TNode jiu9 = new TNode(9, "九洲城", null, null, 2);
    static TNode work33 = new TNode(33, "work", null, null, 5);
    static TNode gao24 = new TNode(24, "高级技校", null, null, 4);
    static TNode gao25 = new TNode(25, "高级技校", null, null, 4);
    static TNode work26 = new TNode(26, "work", null, null, 4);
    static TNode gao14 = new TNode(14, "高级技校", null, null, 3);
    static TNode gao15 = new TNode(15, "高级技校", null, null, 3);
    static TNode jiu7 = new TNode(7, "九洲城", null, null, 2);
    static TNode work30 = new TNode(30, "work", null, null, 4);
    static TNode gao19 = new TNode(19, "高级技校", null, null, 3);
    static TNode work20 = new TNode(20, "work", null, null, 3);
    static TNode gao10 = new TNode(10, "高级技校", null, null, 2);
    static TNode work34 = new TNode(34, "work", null, null, 5);
    static TNode work35 = new TNode(35, "work", null, null, 5);
    //static TNode work36 = new TNode(36, "work", null, null, );
    static TNode work27 = new TNode(27, "work", null, null, 4);
    static TNode work28 = new TNode(28, "work", null, null, 4);
    static TNode work29 = new TNode(29, "work", null, null, 4);
    static TNode work16 = new TNode(16, "work", null, null, 3);
    static TNode work31 = new TNode(31, "work", null, null, 4);
    static TNode work32 = new TNode(32, "work", null, null, 4);
    static TNode work21 = new TNode(21, "work", null, null, 3);
    static TNode work22 = new TNode(22, "work", null, null, 3);
    static TNode work17 = new TNode(17, "work", null, null, 3);
    static TNode work37 = new TNode(37, "work", null, null, 5);
    static TNode work38 = new TNode(38, "work", null, null, 5);
    static TNode work39 = new TNode(39, "work", null, null, 5);
    static TNode work40 = new TNode(40, "work", null, null, 4);
    static TNode work41 = new TNode(41, "work", null, null, 4);
    static TNode work42 = new TNode(42, "work", null, null, 4);
    static TNode work43 = new TNode(43, "work", null, null, 3);

    public BusRoutesTree(){
        root.child = nan1;
        nan1.child = gong4;
        nan1.rSib = gong2;
        gong4.child = xiang11;
        gong4.rSib = xiang5;
        gong2.child = xiang8;
        gong2.rSib = xiang3;
        xiang11.child = jiu23;
        xiang11.rSib = zhu12;
        xiang5.child = jiu13;
        xiang5.rSib = zhu6;
        xiang8.child = jiu18;
        xiang3.child = jiu9;
        jiu23.child = work33;
        jiu23.rSib = gao24;
        zhu12.child = gao25;
        jiu13.child = work26;
        jiu13.child = gao14;
        zhu6.child = gao15;
        zhu6.rSib = jiu7;
        jiu18.child = work30;
        jiu18.rSib = gao19;
        jiu9.child = work20;
        jiu9.rSib = gao10;
        work33.rSib = work34;
        gao24.child = work35;
        //gao25.child = work36;
        work26.rSib = work27;
        gao14.child = work28;
        gao15.child = work29;
        jiu7.child = work16;
        work30.rSib = work31;
        gao19.child = work32;
        work20.rSib = work21;
        gao10.child = work22;
        work16.rSib = work17;
        gao25.child = work37;
        work37.rSib = work38;
        work35.rSib = work39;
        work28.rSib = work40;
        work29.rSib = work41;
        work32.rSib = work42;
        work22.rSib = work43;

    }

}
